name: Deploy CI3 to cPanel via SSH

on:
  push:
    branches:
      - BarrilDev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # (Opsional) Cek error PHP
    
      # Copy file ke server via SSH
      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: advokat.japrime.id
          username: u1485990
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: 22
          script: |
            cd public_html/advokat.japrime.id
            git pull origin BarrilDev || echo "Deploy via rsync"
